### ISSUE TITLE
mttn: Allow greater syscall model flexibility in testing.

### ISSUE THREAD

**Issue by lisaoverall** [trailofbits/sholva#220]
Our current mttn Makefile test setup assumes the Decree syscall model and will do the wrong thing for `make traces` for new tests requiring a Linux syscall model. 

- [ ] Agree on a convention to distinguish between tests that require the Linux syscall model and the Decree syscall model (subdirectories, naming scheme?)
- [ ] Modify `traces` target to have a prerequisite per supported syscall model, according to our chosen convention.

**Comment by lisaoverall** [comment]
Currently we define `ASM_TESTS` in `mttn/test/Makefile`. We could make an `ASM_TESTS_DECREE` and `ASM_TESTS_LINUX`, and reflect this in macros in `mttn/src/trace.rs`.

**Comment by jleightcap** [comment]
> Currently we define ASM_TESTS in mttn/test/Makefile. We could make an ASM_TESTS_DECREE and ASM_TESTS_LINUX, and reflect this in macros in mttn/src/trace.rs.

This solves the problem completely, however I ran into some unexpected complexity regarding defaults, and detecting when to override them (for example, in the tracer self-tests: https://github.com/trailofbits/sholva/pull/222/files#diff-8600299d6d0b11705d1db63cd6dbc96389c2d804353836514003d5665429fb3bL994-R1000)

I went with a temporary solution in https://github.com/trailofbits/sholva/pull/222 from the assumption that we can write our tests assuming Linux. If DECREE-specific tests are required, then a more the more general solution is required.
